<a href="https://colab.research.google.com/github/krithika005/pythoncodes/blob/main/training5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
j=[4, 6, 2, 8, 9]
j

[4, 6, 2, 8, 9]

In [ ]:
1) numpy                      array operations
2) pandas                     Data manipulation and analysis
3) matplotlib and Seaborn     Graphical Analysis
4) sklearn                    Machine learning algorithms and techniques
5) statsmodels                statistical analysis
6) scipy                      statistical analysis

In [5]:
j=[5, 7, 2, 8, 4, 7]
j

[5, 7, 2, 8, 4, 7]

In [8]:
d=np.array(j)

In [9]:
tuple(d)

(5, 7, 2, 8, 4, 7)

In [10]:
type(d)

numpy.ndarray

In [11]:
d

array([5, 7, 2, 8, 4, 7])

In [12]:
d.shape

(6,)

In [13]:
d.ndim

1

In [14]:
d.size

6

In [15]:
s=[[4, 8, 90, 12], [37, 38, 26, 27], [26, 18, 29, 38], [17, 29, 39, 49], [17, 38, 50, 60]]
s

[[4, 8, 90, 12],
 [37, 38, 26, 27],
 [26, 18, 29, 38],
 [17, 29, 39, 49],
 [17, 38, 50, 60]]

In [16]:
type(s)

list

In [20]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [37, 38, 26, 27],
       [26, 18, 29, 38],
       [17, 29, 39, 49],
       [17, 38, 50, 60]])

In [21]:
arr1.shape

(5, 4)

In [22]:
arr1.size

20

In [23]:
arr1.ndim

2

In [24]:
type(arr1)

numpy.ndarray

In [25]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [26]:
h.size

6

In [27]:
h.shape

(2, 3)

In [28]:
h.ndim

2

In [30]:
w=h.reshape(3,2)
w

array([[5, 7],
       [2, 8],
       [4, 7]])

In [31]:
w.shape

(3, 2)

In [32]:
w.size

6

In [33]:
w.ndim

2

In [34]:
m=[1,3,5,38,29,30,48,50,69]
m

[1, 3, 5, 38, 29, 30, 48, 50, 69]

In [37]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [38]:
list(range(3,13,6))

[3, 9]

In [40]:
range(5,500)

range(5, 500)

In [41]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [43]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [44]:
list(range(-1,-10))

[]

In [45]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [46]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [47]:
[2,2.5,3,3.5,4,4.5]

[2, 2.5, 3, 3.5, 4, 4.5]

In [48]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [49]:
range(5,50,5)

range(5, 50, 5)

In [50]:
for i in range(5,50,5):
  print('Data')

Data
Data
Data
Data
Data
Data
Data
Data
Data


In [51]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [52]:
for i in range(5,50,5):
  print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [54]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [55]:
y=[]
x=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])

In [56]:
x

[5, 23, 62, 80, 77, 80]

In [57]:
y

[87, 46, 84, 45, 33]

In [58]:
for i in j:
  print(i)

5
87
23
46
62
84
80
45
77
33
80
