<a href="https://colab.research.google.com/github/krithika005/pythoncodes/blob/main/training9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a=np.random.randint(30,99,(7,8))
a

array([[40, 72, 55, 85, 59, 68, 65, 38],
       [75, 40, 86, 51, 80, 84, 36, 45],
       [59, 56, 77, 38, 44, 95, 37, 95],
       [69, 91, 83, 44, 97, 34, 52, 54],
       [31, 53, 48, 65, 48, 34, 96, 56],
       [52, 83, 30, 88, 48, 48, 64, 76],
       [77, 87, 65, 63, 76, 44, 39, 98]])

In [5]:
a.shape

(7, 8)

In [6]:
a.ndim

2

In [8]:
b=np.random.randint(20,80,(8,9))
b

array([[57, 40, 48, 78, 72, 54, 40, 25, 53],
       [53, 52, 70, 61, 57, 48, 62, 34, 20],
       [29, 58, 66, 22, 77, 38, 48, 65, 73],
       [66, 20, 20, 20, 78, 36, 53, 54, 20],
       [46, 59, 58, 51, 65, 76, 35, 27, 56],
       [68, 57, 73, 39, 76, 23, 28, 45, 57],
       [54, 62, 45, 31, 20, 72, 55, 45, 56],
       [45, 25, 48, 47, 56, 45, 55, 57, 69]])

In [9]:
b.shape

(8, 9)

In [10]:
b.ndim

2

In [11]:
b[7,0]

45

In [15]:
#array[row_start:2 row_end:6 row_step:1 , col_start:1 col_end:7 col_step:1]

In [16]:
b[2:6:1,1:7:1]

array([[58, 66, 22, 77, 38, 48],
       [20, 20, 20, 78, 36, 53],
       [59, 58, 51, 65, 76, 35],
       [57, 73, 39, 76, 23, 28]])

In [17]:
import pandas as pd

In [28]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [29]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [33]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [36]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [43]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [44]:
df.columns

Index(['name', 'sub'], dtype='object')

In [45]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int64

In [47]:
df['sub'].min()

3

In [48]:
df['sub'].max()

50

In [49]:
df['sub'].std()

21.975364995072702

In [50]:
df['sub'].quantile()

8.0

In [51]:
df['sub'].mean()

17.25

In [52]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64

In [53]:
df['sub'].median()

8.0

In [54]:
df['sub'].var()

482.9166666666667