<a href="https://colab.research.google.com/github/krithika005/pythoncodes/blob/main/training6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
d=np.array([10,28,30,39,48])
d

array([10, 28, 30, 39, 48])

In [7]:
np.mean(d)

31.0

In [8]:
np.median(d)

30.0

In [10]:
np.min(d)

10

In [11]:
np.max(d)

48

In [12]:
np.var(d)

160.8

In [13]:
np.std(d)

12.680693987317888

In [18]:
q2=np.quantile(d,0.5)
q2

30.0

In [15]:
np.quantile(d,1)

48

In [19]:
q3=np.quantile(d,0.75)
q3

39.0

In [20]:
q1=np.quantile(d,0.25)
q1

28.0

In [21]:
np.random.rand(10,5)

array([[0.68810839, 0.87486422, 0.44142691, 0.96467893, 0.1783164 ],
       [0.46358745, 0.70404579, 0.34099469, 0.51729768, 0.55119369],
       [0.53376352, 0.08097388, 0.9264224 , 0.72591726, 0.72000277],
       [0.03116537, 0.63154331, 0.44672166, 0.5066697 , 0.36403403],
       [0.71139448, 0.61638104, 0.01160393, 0.69751545, 0.07061255],
       [0.26292931, 0.80612568, 0.18770028, 0.73422416, 0.30514062],
       [0.59243995, 0.32020139, 0.03746047, 0.47322269, 0.75588125],
       [0.8260879 , 0.1426926 , 0.44626668, 0.6562671 , 0.606415  ],
       [0.66184373, 0.36294572, 0.47878863, 0.15026354, 0.0747887 ],
       [0.36477743, 0.31249246, 0.9955214 , 0.82030671, 0.34800876]])

In [25]:
r=np.random.rand(100)
r

array([0.89907833, 0.27110904, 0.76155892, 0.63148631, 0.93667622,
       0.19693024, 0.3244526 , 0.96252757, 0.85869195, 0.85353409,
       0.24633388, 0.69823827, 0.731803  , 0.90435717, 0.62302683,
       0.15238106, 0.08271272, 0.94401265, 0.9604071 , 0.18164853,
       0.91778604, 0.87503198, 0.74084229, 0.20125914, 0.53892906,
       0.22546009, 0.28867813, 0.11102541, 0.28535354, 0.57024529,
       0.73602129, 0.5393598 , 0.97009952, 0.07931589, 0.24171505,
       0.91056986, 0.5737673 , 0.67582286, 0.89394795, 0.46649417,
       0.42717789, 0.66037529, 0.11558946, 0.27598734, 0.31118416,
       0.58814233, 0.31494996, 0.06441754, 0.60826289, 0.18823743,
       0.90807709, 0.14936123, 0.88993887, 0.93160724, 0.11166914,
       0.21977935, 0.79507882, 0.43610862, 0.64651552, 0.41576408,
       0.72321806, 0.25836019, 0.31383827, 0.00829119, 0.54766038,
       0.2723988 , 0.90785061, 0.96860961, 0.56567146, 0.11804251,
       0.67839256, 0.85374594, 0.39085148, 0.7601101 , 0.84353

In [26]:
r.size

100

In [27]:
r.ndim

1

In [28]:
r.shape

(100,)

In [29]:
r=np.random.rand(10,5)
r

array([[0.48395809, 0.0570253 , 0.28884075, 0.87774576, 0.28793416],
       [0.37313085, 0.92163839, 0.43665756, 0.71043409, 0.35769055],
       [0.78782709, 0.48518065, 0.97459687, 0.21087498, 0.81224094],
       [0.77802486, 0.5599364 , 0.20921683, 0.34701744, 0.71308955],
       [0.88495582, 0.51060107, 0.52196262, 0.90776422, 0.78228025],
       [0.59211321, 0.4168371 , 0.9444424 , 0.60858759, 0.05888361],
       [0.73656698, 0.97691528, 0.14889608, 0.99246485, 0.97553128],
       [0.03020396, 0.80375044, 0.96443185, 0.50118158, 0.45577382],
       [0.22397934, 0.8136543 , 0.88606223, 0.71581613, 0.89051764],
       [0.97243014, 0.98746247, 0.90139031, 0.71348329, 0.64987777]])

In [31]:
r.ndim

2

In [32]:
r.size

50

In [33]:
r.shape

(10, 5)

In [37]:
s=np.random.randn(5,4,3)
s

array([[[ 0.57382312,  0.65808096,  0.15715285],
        [-0.08936152,  0.12365737, -1.32476449],
        [ 0.15749619, -1.18706368, -1.67383927],
        [ 0.99080813, -0.71180244, -0.13008051]],

       [[-1.1245244 , -0.14602996, -1.29722772],
        [ 0.86937238, -0.59700469, -0.01008858],
        [-0.97260549,  0.44925626,  0.64767334],
        [ 0.34905736, -0.01329223,  1.05691639]],

       [[-2.53497619, -0.01574927, -0.28501224],
        [-0.55950909,  0.46174787,  0.52886457],
        [-1.65174076,  1.26010949, -0.68102658],
        [ 0.27810355,  0.02767114, -1.93637699]],

       [[ 0.02743167, -0.7135361 ,  0.86125952],
        [ 1.12016201, -0.92376252, -0.85079241],
        [ 1.69629723, -0.27155011, -0.72642405],
        [ 1.82924774,  0.39908575,  1.75776547]],

       [[-1.57134555,  0.01484702,  0.66004145],
        [ 0.53967908,  0.52593874, -0.48717687],
        [-1.43481698,  0.27002245,  0.49965303],
        [ 0.76130847, -0.57709794, -2.245993  ]]])

In [38]:
np.random.rand()

0.03987684093633215

In [44]:
np.random.normal(6,5,4)

array([ 6.57808965, 10.75253807,  4.08904584,  8.15913036])

In [45]:
np.random.normal(10,3)

13.76002618472306

In [46]:
np.random.normal(30,2,(2,1))

array([[30.72318951],
       [31.87703081]])

In [51]:
np.random.randint(23,56,100)

array([37, 30, 29, 46, 50, 55, 32, 46, 44, 32, 33, 40, 52, 39, 27, 39, 50,
       27, 53, 39, 25, 37, 55, 46, 52, 40, 23, 30, 35, 32, 48, 53, 35, 33,
       51, 31, 40, 53, 41, 53, 38, 49, 39, 35, 38, 41, 47, 30, 44, 33, 38,
       26, 43, 34, 48, 36, 32, 30, 34, 24, 48, 38, 29, 49, 45, 28, 27, 42,
       45, 28, 28, 30, 41, 34, 55, 24, 33, 33, 34, 53, 55, 32, 31, 55, 28,
       31, 31, 39, 30, 53, 28, 36, 26, 47, 51, 26, 44, 42, 36, 23])

In [52]:
np.random.randint(35,86,(5,5))

array([[85, 36, 66, 82, 73],
       [48, 43, 76, 49, 84],
       [85, 71, 85, 37, 76],
       [47, 36, 85, 41, 63],
       [83, 47, 72, 47, 67]])